name: Deploy OneFoodDialer

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  test:
    name: Test & Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint:check

      - name: Check formatting
        run: npm run format:check

      - name: Run unit tests
        run: npm run test:ci
        env:
          # Provide minimal environment for tests
          NODE_ENV: test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        if: success()
        with:
          file: ./coverage/lcov.info
          fail_ci_if_error: false

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Validate required secrets
        run: |
          if [ -z "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}" ]; then
            echo "❌ NEXT_PUBLIC_SUPABASE_URL secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" ]; then
            echo "❌ NEXT_PUBLIC_SUPABASE_ANON_KEY secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.DATABASE_URL }}" ]; then
            echo "❌ DATABASE_URL secret is not set"
            exit 1
          fi
          echo "✅ All required secrets are configured"

      - name: Build application
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-files
          path: .next/

  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    outputs:
      preview_url: ${{ steps.deploy.outputs.preview_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate Vercel secrets
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "❌ VERCEL_TOKEN secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "❌ VERCEL_ORG_ID secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "❌ VERCEL_PROJECT_ID secret is not set"
            exit 1
          fi
          echo "✅ All Vercel secrets are configured"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Generate Prisma Client for Preview
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --confirm)
          echo "preview_url=$url" >> $GITHUB_OUTPUT
          echo "✅ Preview deployed to: $url"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Comment PR with preview URL
        uses: actions/github-script@v6
        if: success()
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment ready!\n\n**Preview URL:** ${{ steps.deploy.outputs.preview_url }}\n\n✅ Build completed successfully`
            })

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    outputs:
      production_url: ${{ steps.deploy.outputs.production_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Validate Vercel secrets
        run: |
          if [ -z "${{ secrets.VERCEL_TOKEN }}" ]; then
            echo "❌ VERCEL_TOKEN secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VERCEL_ORG_ID }}" ]; then
            echo "❌ VERCEL_ORG_ID secret is not set"
            exit 1
          fi
          if [ -z "${{ secrets.VERCEL_PROJECT_ID }}" ]; then
            echo "❌ VERCEL_PROJECT_ID secret is not set"
            exit 1
          fi
          echo "✅ All Vercel secrets are configured"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Remove existing Vercel configuration
        run: rm -rf .vercel || true

      - name: Link Vercel project
        run: vercel link --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Generate Prisma Client for Production
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}

      - name: Deploy Project Artifacts to Vercel
        id: deploy
        run: |
          url=$(vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm)
          echo "production_url=$url" >> $GITHUB_OUTPUT
          echo "✅ Production deployed to: $url"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Run health check
        run: |
          echo "⏳ Waiting for deployment to be ready..."
          sleep 30
          echo "🔍 Running health check..."

          # Try multiple public health check endpoints (bypass SSO protection)
          HEALTH_URLS=(
            "${{ steps.deploy.outputs.production_url }}/status"
            "${{ steps.deploy.outputs.production_url }}/ping"
            "${{ steps.deploy.outputs.production_url }}/health.json"
            "${{ steps.deploy.outputs.production_url }}/api/status"
            "${{ steps.deploy.outputs.production_url }}/health-check"
            "${{ steps.deploy.outputs.production_url }}/health"
            "${{ steps.deploy.outputs.production_url }}/api/health"
          )

          for url in "${HEALTH_URLS[@]}"; do
            echo "Testing: $url"

            # Get response with status code
            response=$(curl -s -w "\n%{http_code}" "$url" || echo -e "\nERROR")
            http_code=$(echo "$response" | tail -n1)
            body=$(echo "$response" | head -n -1)

            echo "HTTP Status: $http_code"
            echo "Response Body: $body"

            if [ "$http_code" = "200" ]; then
              echo "✅ Health check passed for $url"

              # For simple text responses (like /status, /ping)
              if echo "$body" | grep -q -E "(OK|pong|ok|running)" || echo "$body" | grep -q '"status"'; then
                echo "✅ Health check response is valid: $body"
                exit 0
              else
                echo "⚠️ Health check returned 200 but unexpected response: $body"
                # Still consider it a success if we got 200
                exit 0
              fi
            elif [ "$http_code" = "401" ]; then
              echo "❌ Health check failed with 401 Unauthorized - SSO protection detected"
              echo "This indicates Vercel project has SSO/Password protection enabled"
              echo "To fix: Go to Vercel Dashboard → Settings → Security → Disable Password Protection"
            elif [ "$http_code" = "404" ]; then
              echo "⚠️ Health check endpoint not found (404) - trying next endpoint"
            else
              echo "❌ Health check failed with HTTP $http_code"
            fi

            echo "---"
          done

          echo "❌ All health check endpoints failed"
          exit 1

      - name: Check Sentry configuration
        id: sentry-check
        run: |
          if [ -n "${{ secrets.SENTRY_AUTH_TOKEN }}" ]; then
            echo "sentry_configured=true" >> $GITHUB_OUTPUT
          else
            echo "sentry_configured=false" >> $GITHUB_OUTPUT
          fi

      - name: Notify Sentry of deployment
        uses: getsentry/action-release@v1
        if: ${{ success() && steps.sentry-check.outputs.sentry_configured == 'true' }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ github.sha }}

  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: deploy-preview
    if: (github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')) && needs.deploy-preview.outputs.preview_url != ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Determine test URL
        id: test-url
        run: |
          if [ -n "${{ needs.deploy-preview.outputs.preview_url }}" ]; then
            TEST_URL="${{ needs.deploy-preview.outputs.preview_url }}"
            echo "Using preview URL: $TEST_URL"
          else
            TEST_URL="https://onefooddialer-js-ld42.vercel.app"
            echo "Using production URL: $TEST_URL"
          fi
          echo "test_url=$TEST_URL" >> $GITHUB_OUTPUT
          echo "✅ Running E2E tests against: $TEST_URL"

      - name: Wait for deployment to be ready
        run: |
          echo "⏳ Waiting for deployment to be ready..."
          sleep 30

          # Test if the deployment is accessible
          for i in {1..5}; do
            if curl -s -f "${{ steps.test-url.outputs.test_url }}/status" > /dev/null; then
              echo "✅ Deployment is ready"
              break
            fi
            echo "⏳ Attempt $i/5: Waiting for deployment..."
            sleep 10
          done

      - name: Run E2E tests
        run: npm run test:e2e
        env:
          BASE_URL: ${{ steps.test-url.outputs.test_url }}
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.test-url.outputs.test_url }}

      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
